import { useState } from 'react';
import { VizScene } from './components/VizScene';
import { SearchOverlay } from './components/SearchOverlay';
import { MusicPlayer } from './components/MusicPlayer';
import type { GraphData } from './components/Graph';

function App() {
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<GraphData | null>(null);
  const [shouldPlayMusic, setShouldPlayMusic] = useState(false);

  const handleSearch = async (query: string) => {
    setLoading(true);
    setShouldPlayMusic(true);
    try {
      // In a real scenario, fetch from the backend:
      // const res = await fetch('http://localhost:8000/api/v1/ask', {
      //     method: 'POST',
      //     headers: { 'Content-Type': 'application/json' },
      //     body: JSON.stringify({ text: query })
      // });
      // const result = await res.json();

      // Mocking response for visualization purposes immediately
      await new Promise(resolve => setTimeout(resolve, 1000));

      const mockData: GraphData = {
        question: query,
        answer: "This is a simulated answer generated by DSPy.",
        context: {
          kg: "Simulated KG Data",
          papers: "Simulated Spanner Data"
        }
      };

      setData(mockData);
    } catch (error) {
      console.error("Search failed:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <SearchOverlay onSearch={handleSearch} loading={loading} />
      <VizScene data={data} />
      <MusicPlayer playTrigger={shouldPlayMusic} />
    </>
  );
}

export default App;
